---
title: "simpsons_guests"
author: "Paul Dong"
date: "2019/9/9"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
theme_set(theme_light())
simpsons <- readr::read_delim("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-08-27/simpsons-guests.csv", delim = "|", quote = "") %>% 
  mutate(self = str_detect(role, "sel|selves"))
```

```{r}
simpsons %>% 
  count(guest_star, role, sort = T) %>% 
  filter(role == "Himself" | role == "Herself") # or filter(role %in% c("Himself", "Herself"))
```

```{r}

simpsons %>% 
  count(guest_star, role, sort = T) %>% 
  filter(str_detect(role, "sel")) %>% 
  View
```

```{r}
simpsons %>% 
  filter(self) %>% 
  count(guest_star, sort = T) %>% 
  # arrange(n) %>% 
  filter(n>1) %>% 
  mutate(guest_star = fct_reorder(guest_star, n)) %>% 
  ggplot(aes(guest_star, n))+
  geom_col()+
  coord_flip() +
  labs(title = "Who has played themselves in multiple Simpsons episodes?")
```

Has the frequency of guest stars changed with time?

```{r}
simpsons %>% 
  separate_rows(role, sep = ";\\s+") %>% 
  add_count(role) %>% 
  filter(n>8) %>% 
  count(season = parse_number(season), role) %>% 
  mutate(role = fct_reorder(role, -n, sum)) %>% 
  ggplot(aes(season, n)) +
  geom_col()+
  facet_wrap(~role)
```

```{r}
simpsons_dataset <- read_csv(here::here("data", "simpsons_dataset.csv")) %>% 
  select(role = raw_character_text, line = spoken_words)
   
```
```{r}
simpsons_dataset %>% 
  count(role, sort = T) %>% 
  semi_join(simpsons, by = "role")
```
```{r}
(guest_processed <- simpsons %>% 
   mutate(role = ifelse(self, guest_star, role)))

simpsons %>% 
  count(role, sort = T) %>% 
  anti_join(simpsons_dataset, by = "role")
```

