---
title: "bird collisions graphs"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(here)
# library(jkmisc)
library(patchwork)

bird_collisions <- read_csv("bird_collisions.csv")

```
```{r}
plot_data <- bird_collisions %>%
  filter(locality == "CHI") %>% 
  mutate(month = month(date),
         year = year(date)) %>% 
  unite("binomial_name", genus, species, sep = " ") %>% 
  count(year, month, binomial_name) %>% 
  complete(nesting(year, binomial_name), month = 1:12, fill = list(n = 0)) %>%  #combinatrics 
  group_by(year, binomial_name) %>% 
  mutate(percent = n/sum(n)) %>% #perc of this year
  mutate(percent = ifelse(is.nan(percent), 0, percent))
```
```{r, fig.width = 13, fig.height = 10}
ggplot(plot_data, aes(x = month, y = percent, fill = binomial_name)) +
  geom_area(size = 0, position = position_dodge(), alpha = 0.2) +
  scale_x_continuous(labels = month.abb, breaks = 1:12)+
  scale_fill_viridis_d("Year", option = "plasma", direction = 1) +
  scale_color_viridis_d(option = "plasma", direction = 1) +
  labs(x = NULL,
       y = NULL,
       title = "Overall")+
  coord_polar()+
    theme(axis.text = element_blank(),
        legend.position = "none")

```


```{r}
flower <- ggplot(plot_data, aes(x = month, y = percent, fill = binomial_name)) +
  geom_area(size = 0, position = position_dodge(), alpha = 0.2) +
  scale_x_continuous(labels = month.abb, breaks = 1:12) +
  scale_y_continuous(limits = c(0,1), breaks = c(0.5, 0.1)) +
  scale_fill_viridis_d("Year", option = "plasma", direction = 1) +
  scale_color_viridis_d(option = "plasma", direction = 1) +
  guides(fill = guide_colorbar()) +
  coord_polar() +
  labs(x = NULL,
       y = NULL,
       title = "Overall") +
  # theme_jk(dark = FALSE, grid = "X", strip_text_size = 10, plot_title_size = 14) +
  theme(axis.text = element_blank(),
        legend.position = "none")
flower
```
```{r}
library(RColorBrewer)
library(ggthemes)

```

```{r}
bird_collisions_munge <- bird_collisions %>%
  mutate(location = case_when(
    locality == "CHI" ~ "Elsewhere in Chicago",
    locality == "MP" ~ "McCormick Place"
  ))
```

```{r}
### Data for p1 - all collisions by year 
total <- bird_collisions_munge %>%
  mutate(year = year(ymd(date))) %>%
  group_by(year) %>%
  mutate(collisions = n()) %>%
  select(year, collisions) %>%
  unique()
```
```{r}
total2 <- bird_collisions_munge %>% 
  mutate(year = year(ymd(date))) %>%
  count(year)
```

```{r}
### Data for p2 - all collisions by year and location
total_local <- bird_collisions_munge %>%
  mutate(year = year(ymd(date))) %>%
  group_by(year, location) %>%
  mutate(collisions = n()) %>%
  select(year, location, collisions) %>%
  unique()
```
```{r}
total_local2 <-  bird_collisions_munge %>% 
  mutate(year = year(ymd(date))) %>%
  count(year, location)
```
```{r}
### p1 - all collisions by year 
p1 <- ggplot(data = total2,
             aes(x = year,
                 y = n)) +
  geom_line(color = "#6F9283",
            size = 1) +
  #geom_point(color = "#6F9283") + 
  theme_fivethirtyeight() + 
  labs(title = "1. Total reported collisions by year",
       subtitle = "There were more collisions reported in 2006-2016 than in earlier years.
The trend of the data changed in the early 2000s as well")
p1
```
```{r}
### p2 - all collisions by year and location
p2 <- ggplot(data = total_local2,
             aes(x = year,
                 y = n,
                 group = location)) +
  geom_vline(xintercept=2002,
             colour="#C7958D",
             size = 2) +
  geom_line(aes(color = location),
            size = 1) +
  #geom_point(aes(color = location)) + 
  ylim(0, 4000) +
  scale_color_manual(values=c("#6F9283", "#654C4F")) +
  theme_fivethirtyeight() + 
  labs(title = "2. Reported collisions by year and location",
       subtitle = "Collisions at McCormick Place have generally decreased, 
but collisions elsewhere in Chicago have greatly increased.") +
  annotate("label",
           x = 1978,
           y = 3800,
           fill = "#F0F0F0",
           alpha = .75,
           label.size = NA,
           color = "#3C3C3C",
           label = "3. Cause of increase in reports:",
           fontface = 2,
           size = 5,
           hjust = 0) + 
  annotate("label",
           x = 1978, 
           y = 2900, 
           fill = "#F0F0F0",
           alpha = .75, 
           label.size = NA, 
           color = "#3C3C3C",
           label = "The Chicago Bird Collision Monitors began 
collision monitoring efforts throughout 
downtown Chicago in 2002.",
           hjust = 0) +
  theme(legend.title = element_blank())
p2
```
```{r}
### Data for p3 - all collisions by month, year, and location
month_year <- bird_collisions_munge %>%
  mutate(lubdate = ymd(date),
         year = year(lubdate),
         monthofyear = month(lubdate,
                             label = TRUE,
                             abbr = TRUE)) %>%
  group_by(year, monthofyear, location) %>%
  count(name = "collisions")
```

```{r}
### p3 - all collisions by month, year, and location
p3 <- ggplot(data = month_year,
             aes(x=year,
                 y=collisions,
                 group = location)) +
  geom_vline(xintercept=2002,
             colour="#C7958D",
             size = 2) +
  geom_line(aes(color = location),
            size = 1) +
  scale_color_manual(values=c("#6F9283", "#654C4F")) +
  facet_wrap("monthofyear", ncol=4) + 
  theme_fivethirtyeight() + 
  labs(title = "4. Reported collisions by year, location, and month",
       subtitle = "Only collisions during migratory months are recorded. Most of the new collision reports are from May, September, and October
of each year and from around Chicago, not McCormick Place. The conclusion? Collisions may not be increasing, but reporting is.") +
  theme(legend.title = element_blank())
p3
```
```{r, fig.width = 13, fig.height = 10}
p_assemble <- (p1 | p2) / p3
p_assemble + 
  plot_annotation(title = "Are more birds colliding with buildings in Chicago?",
                  subtitle = "Probably not, but more collisions are being reported.",
                  caption = "Winger BM, Weeks BC, Farnsworth A, Jones AW, Hennen M, Willard DE (2019)
                  Nocturnal flight-calling behaviour predicts vulnerability to artificial light in migratory birds. 
                  Proceedings of the Royal Society B 286(1900): 20190364. 
                  https://doi.org/10.1098/rspb.2019.0364",
                  theme = theme_fivethirtyeight())
                
```
```{r}
ggsave("collisions.png", width = 13, height = 10, units = c("in"))
```

